---
title: "ggpot_1"
author: "Maya Spaur"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df

view(weather_df)
```
#aesthetic mapping inside geom_pint to add color

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)
```
#alternate way of making plot using piping

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point(aes(color = name), alpha = .5) + geom_smooth(se = FALSE)

```


facet! create grid of individual panels

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  geom_smooth(se = FALSE) + 
  facet_grid(~name)

```

let's make it more interesting. 

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax))


weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size=prcp), alpha = .2) + 
  geom_smooth(size= 2, se = FALSE)

```
